# Generated by Django 5.2.7 on 2025-11-06 00:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('COORDINADOR', 'Coordinador'), ('TERAPEUTA', 'Terapeuta'), ('RECEPCIONISTA', 'Recepcionista'), ('MEDICO', 'Médico'), ('PSICOLOGO', 'Psicólogo')], default='TERAPEUTA', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Rol')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido. Ej: +5212345678901', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('cedula_profesional', models.CharField(blank=True, help_text='Cédula profesional para personal médico/terapéutico', max_length=20, null=True, unique=True, verbose_name='Cédula Profesional')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=15, verbose_name='Estado')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/', verbose_name='Foto de Perfil')),
                ('fecha_contratacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales sobre el usuario', verbose_name='Notas')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidades', models.CharField(blank=True, choices=[('PSICOLOGIA', 'Psicología'), ('LENGUAJE', 'Terapia del Lenguaje'), ('OCUPACIONAL', 'Terapia Ocupacional'), ('FISICA', 'Terapia Física'), ('PSIQUIATRIA', 'Psiquiatría'), ('NEUROLOGIA', 'Neurología'), ('CONDUCTUAL', 'Análisis Conductual (ABA)'), ('INTEGRACION_SENSORIAL', 'Integración Sensorial'), ('MUSICA', 'Musicoterapia'), ('ARTE', 'Arte Terapia')], max_length=30, verbose_name='Especialidad Principal')),
                ('especialidades_secundarias', models.JSONField(blank=True, default=list, help_text='Lista de especialidades adicionales', verbose_name='Especialidades Secundarias')),
                ('universidad', models.CharField(blank=True, max_length=200, verbose_name='Universidad')),
                ('anios_experiencia', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('certificaciones', models.JSONField(blank=True, default=list, help_text='Lista de certificaciones y cursos especializados', verbose_name='Certificaciones')),
                ('bio', models.TextField(blank=True, help_text='Descripción de experiencia y enfoque terapéutico', verbose_name='Biografía Profesional')),
                ('horario_atencion', models.JSONField(blank=True, default=dict, help_text='Horarios disponibles por día de la semana', verbose_name='Horario de Atención')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible para Asignaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acceso', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('INTENTO_FALLIDO', 'Intento Fallido')], max_length=20, verbose_name='Tipo de Acceso')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('exitoso', models.BooleanField(default=True, verbose_name='Acceso Exitoso')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol', 'estado'], name='usuarios_us_rol_74df2e_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='usuarios_us_email_41a027_idx'),
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['usuario', '-fecha_hora'], name='usuarios_re_usuario_ea4bed_idx'),
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['tipo_acceso', 'fecha_hora'], name='usuarios_re_tipo_ac_95aa75_idx'),
        ),
    ]
