# Generated by Django 5.0 on 2026-01-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero_identificacion',
            field=models.CharField(blank=True, help_text='Documento de identidad del usuario', max_length=20, null=True, verbose_name='Número de Identificación'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Pasaporte'), ('RC', 'Registro Civil'), ('NIT', 'NIT')], default='CC', max_length=3, verbose_name='Tipo de Identificación'),
        ),
    ]
