# Generated by Django 5.0 on 2026-01-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_numero_identificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_identificacion',
            field=models.CharField(help_text='Documento de identidad del usuario', max_length=20, unique=True, verbose_name='Número de Identificación'),
        ),
    ]
