# Generated by Django 5.0 on 2025-12-16 18:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_alter_asignaciongrupo_numero_terapias_asignadas'),
        ('procedimientos', '0012_valoracioninicial_diagnostico_cie10_texto'),
        ('terapias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evolucionpaciente',
            options={'ordering': ['-fecha_sesion', '-hora_inicio'], 'verbose_name': 'Evolución de Paciente', 'verbose_name_plural': 'Evoluciones de Pacientes'},
        ),
        migrations.RemoveIndex(
            model_name='evolucionpaciente',
            name='procedimien_pacient_2961f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='evolucionpaciente',
            name='procedimien_profesi_382de8_idx',
        ),
        migrations.RemoveField(
            model_name='evolucionpaciente',
            name='archivos_adjuntos',
        ),
        migrations.RemoveField(
            model_name='evolucionpaciente',
            name='cambios_medicacion',
        ),
        migrations.RemoveField(
            model_name='evolucionpaciente',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='evolucionpaciente',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='evolucionpaciente',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='evolucionpaciente',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='evolucionpaciente',
            name='observaciones_comunicacion',
        ),
        migrations.RemoveField(
            model_name='evolucionpaciente',
            name='observaciones_socializacion',
        ),
        migrations.RemoveField(
            model_name='evolucionpaciente',
            name='sesion',
        ),
        migrations.RemoveField(
            model_name='evolucionpaciente',
            name='tipo_nota',
        ),
        migrations.RemoveField(
            model_name='evolucionpaciente',
            name='titulo',
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='actividades_realizadas',
            field=models.TextField(blank=True, help_text='Descripción de actividades y ejercicios realizados', verbose_name='Actividades Realizadas'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='asistio',
            field=models.BooleanField(default=True, verbose_name='Asistió a la Sesión'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='desempeno',
            field=models.CharField(blank=True, choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('REQUIERE_APOYO', 'Requiere Apoyo'), ('NO_PARTICIPO', 'No Participó')], max_length=20, verbose_name='Desempeño del Paciente'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='dificultades_observadas',
            field=models.TextField(blank=True, help_text='Dificultades o retos encontrados', verbose_name='Dificultades Observadas'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='fecha_sesion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la Sesión'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='firmado',
            field=models.BooleanField(default=False, help_text='Indica si la evolución ha sido finalizada y firmada', verbose_name='Evolución Firmada'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evoluciones_grupo', to='grupos.grupoterapeutico', verbose_name='Grupo Terapéutico'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Fin'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='logros_obtenidos',
            field=models.TextField(blank=True, help_text='Avances y logros observados en la sesión', verbose_name='Logros Obtenidos'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='material_utilizado',
            field=models.TextField(blank=True, help_text='Material didáctico o recursos utilizados', verbose_name='Material Utilizado'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='nivel_atencion',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1=Muy bajo, 5=Excelente', null=True, verbose_name='Nivel de Atención (1-5)'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='nivel_colaboracion',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Nivel de Colaboración (1-5)'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='nivel_comprension',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Nivel de Comprensión (1-5)'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='nivel_participacion',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Nivel de Participación (1-5)'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='numero_sesion',
            field=models.IntegerField(default=1, help_text='Sesión número X del total asignado', verbose_name='Número de Sesión'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='objetivos_trabajados',
            field=models.TextField(blank=True, help_text='Objetivos terapéuticos abordados en la sesión', verbose_name='Objetivos Trabajados'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='observaciones_generales',
            field=models.TextField(blank=True, verbose_name='Observaciones Generales'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='proximos_objetivos',
            field=models.TextField(blank=True, help_text='Objetivos para trabajar en próximas sesiones', verbose_name='Próximos Objetivos'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='recomendaciones',
            field=models.TextField(blank=True, help_text='Recomendaciones para próximas sesiones o para el hogar', verbose_name='Recomendaciones'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='tarea_asignada',
            field=models.TextField(blank=True, help_text='Tareas o ejercicios para realizar en casa', verbose_name='Tarea Asignada'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='terapia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evoluciones_terapias', to='terapias.terapia', verbose_name='Terapia'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='tipo_sesion',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal'), ('EVALUACION', 'Evaluación'), ('INTERCONSULTA', 'Interconsulta')], default='GRUPAL', max_length=20, verbose_name='Tipo de Sesión'),
        ),
        migrations.AddField(
            model_name='evolucionpaciente',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
        migrations.AlterField(
            model_name='evolucionpaciente',
            name='observaciones_conducta',
            field=models.TextField(blank=True, help_text='Aspectos conductuales relevantes', verbose_name='Observaciones de Conducta'),
        ),
        migrations.AlterField(
            model_name='evolucionpaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones_paciente', to='procedimientos.paciente', verbose_name='Paciente'),
        ),
        migrations.AddIndex(
            model_name='evolucionpaciente',
            index=models.Index(fields=['paciente', 'fecha_sesion'], name='procedimien_pacient_d67112_idx'),
        ),
        migrations.AddIndex(
            model_name='evolucionpaciente',
            index=models.Index(fields=['profesional', 'fecha_sesion'], name='procedimien_profesi_a03c89_idx'),
        ),
        migrations.AddIndex(
            model_name='evolucionpaciente',
            index=models.Index(fields=['terapia', 'fecha_sesion'], name='procedimien_terapia_ac659f_idx'),
        ),
    ]
