# Generated by Django 5.0 on 2025-11-07 00:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTerapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Terapia del Lenguaje, Terapia Ocupacional', max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('codigo', models.CharField(help_text='Código único de identificación', max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría y qué incluye', verbose_name='Descripción')),
                ('color', models.CharField(default='#007bff', help_text='Color en formato hexadecimal (#RRGGBB)', max_length=7, verbose_name='Color')),
                ('icono', models.CharField(blank=True, help_text='Clase de icono (Font Awesome, Bootstrap Icons, etc.)', max_length=50, verbose_name='Icono')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor primero)', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Categoría de Terapia',
                'verbose_name_plural': 'Categorías de Terapias',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['codigo'], name='terapias_ca_codigo_cf5eb2_idx'), models.Index(fields=['activo', 'orden'], name='terapias_ca_activo_7df310_idx')],
            },
        ),
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la terapia', max_length=200, unique=True, verbose_name='Nombre de la Terapia')),
                ('codigo', models.CharField(help_text='Código único de identificación', max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la terapia', verbose_name='Descripción')),
                ('descripcion_corta', models.CharField(blank=True, help_text='Resumen breve para listados', max_length=300, verbose_name='Descripción Corta')),
                ('modalidad', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal'), ('FAMILIAR', 'Familiar'), ('PAREJA', 'En Pareja'), ('MIXTA', 'Mixta')], default='INDIVIDUAL', max_length=20, verbose_name='Modalidad')),
                ('especialidad', models.CharField(choices=[('LENGUAJE', 'Lenguaje y Comunicación'), ('OCUPACIONAL', 'Terapia Ocupacional'), ('FISICA', 'Terapia Física'), ('PSICOLOGIA', 'Psicología'), ('CONDUCTUAL', 'Terapia Conductual (ABA)'), ('INTEGRACION_SENSORIAL', 'Integración Sensorial'), ('MUSICOTERAPIA', 'Musicoterapia'), ('ARTETERAPIA', 'Arteterapia'), ('NEUROLOGICA', 'Terapia Neurológica'), ('SOCIAL', 'Habilidades Sociales'), ('COGNITIVA', 'Estimulación Cognitiva'), ('ALIMENTACION', 'Terapia de Alimentación')], max_length=30, verbose_name='Especialidad')),
                ('nivel_intensidad', models.CharField(choices=[('BAJA', 'Intensidad Baja'), ('MEDIA', 'Intensidad Media'), ('ALTA', 'Intensidad Alta'), ('MUY_ALTA', 'Intensidad Muy Alta')], default='MEDIA', max_length=10, verbose_name='Nivel de Intensidad')),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Duración estándar de la sesión en minutos', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)], verbose_name='Duración (minutos)')),
                ('duracion_minima_minutos', models.PositiveIntegerField(blank=True, help_text='Duración mínima permitida', null=True, validators=[django.core.validators.MinValueValidator(15)], verbose_name='Duración Mínima (minutos)')),
                ('duracion_maxima_minutos', models.PositiveIntegerField(blank=True, help_text='Duración máxima permitida', null=True, validators=[django.core.validators.MaxValueValidator(480)], verbose_name='Duración Máxima (minutos)')),
                ('frecuencia_semanal_recomendada', models.PositiveIntegerField(default=1, help_text='Número de sesiones recomendadas por semana', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Frecuencia Semanal Recomendada')),
                ('costo_sesion', models.DecimalField(decimal_places=2, help_text='Costo estándar por sesión individual', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo por Sesión')),
                ('costo_minimo', models.DecimalField(blank=True, decimal_places=2, help_text='Costo mínimo (si aplica descuento)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo Mínimo')),
                ('costo_paquete_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de paquete mensual (si aplica)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo Paquete Mensual')),
                ('permite_descuento', models.BooleanField(default=True, verbose_name='Permite Descuento')),
                ('edad_minima', models.PositiveIntegerField(blank=True, help_text='Edad mínima recomendada en años', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Edad Mínima')),
                ('edad_maxima', models.PositiveIntegerField(blank=True, help_text='Edad máxima recomendada en años', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Edad Máxima')),
                ('requiere_evaluacion_previa', models.BooleanField(default=True, help_text='Indica si requiere evaluación antes de iniciar', verbose_name='Requiere Evaluación Previa')),
                ('requiere_orden_medica', models.BooleanField(default=False, verbose_name='Requiere Orden Médica')),
                ('capacidad_minima', models.PositiveIntegerField(default=1, help_text='Número mínimo de pacientes (para grupales)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Capacidad Mínima')),
                ('capacidad_maxima', models.PositiveIntegerField(default=1, help_text='Número máximo de pacientes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Capacidad Máxima')),
                ('requiere_acompanante', models.BooleanField(default=False, help_text='Indica si el paciente debe estar acompañado', verbose_name='Requiere Acompañante')),
                ('tipos_consultorio_requeridos', models.JSONField(blank=True, default=list, help_text='Lista de tipos de consultorio compatibles', verbose_name='Tipos de Consultorio Requeridos')),
                ('equipamiento_requerido', models.JSONField(blank=True, default=list, help_text='Lista de equipamiento necesario', verbose_name='Equipamiento Requerido')),
                ('objetivos', models.TextField(blank=True, help_text='Objetivos terapéuticos', verbose_name='Objetivos')),
                ('metodologia', models.TextField(blank=True, help_text='Metodología y técnicas utilizadas', verbose_name='Metodología')),
                ('beneficios', models.TextField(blank=True, help_text='Beneficios esperados de la terapia', verbose_name='Beneficios')),
                ('contraindicaciones', models.TextField(blank=True, help_text='Casos en los que no se recomienda', verbose_name='Contraindicaciones')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('disponible_online', models.BooleanField(default=False, help_text='Puede realizarse de forma virtual', verbose_name='Disponible Online')),
                ('disponible_domicilio', models.BooleanField(default=False, help_text='Puede realizarse en casa del paciente', verbose_name='Disponible a Domicilio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='terapias/imagenes/', verbose_name='Imagen de la Terapia')),
                ('folleto_url', models.URLField(blank=True, help_text='Enlace a folleto informativo', verbose_name='URL del Folleto')),
                ('video_url', models.URLField(blank=True, help_text='Enlace a video explicativo', verbose_name='URL del Video')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar en página principal', verbose_name='Destacado')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terapias', to='terapias.categoriaterapia', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Terapia',
                'verbose_name_plural': 'Terapias',
                'ordering': ['categoria', 'orden', 'nombre'],
                'indexes': [models.Index(fields=['codigo'], name='terapias_te_codigo_b227c8_idx'), models.Index(fields=['categoria', 'activo'], name='terapias_te_categor_214abe_idx'), models.Index(fields=['especialidad'], name='terapias_te_especia_5a597c_idx'), models.Index(fields=['modalidad'], name='terapias_te_modalid_d26720_idx'), models.Index(fields=['activo', 'destacado'], name='terapias_te_activo_0507bc_idx')],
            },
        ),
    ]
