# Generated by Django 5.0 on 2025-12-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0005_paciente_fecha_firma_acudiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numero_admision',
            field=models.CharField(blank=True, help_text='Número de admisión del paciente (manual)', max_length=10, null=True, verbose_name='Número de Admisión'),
        ),
    ]
