# Generated by Django 5.0 on 2025-12-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0006_alter_paciente_numero_admision'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_firma_acudiente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Firma'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='firma_acudiente',
            field=models.TextField(blank=True, help_text='Firma del acudiente en formato base64', verbose_name='Firma Digital Acudiente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ip_firma',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP donde se firmó'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('ADMITIDO', 'Admitido - Sin Valorar'), ('PENDIENTE_VALORACION', 'Pendiente Valoración'), ('PENDIENTE_ASIGNACION', 'Pendiente Asignación Terapias'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('DADO_ALTA', 'Dado de Alta')], default='ACTIVO', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_admision',
            field=models.CharField(blank=True, help_text='Número de admisión del paciente (manual)', max_length=10, null=True, unique=True, verbose_name='Número de Admisión'),
        ),
    ]
