# Generated by Django 5.0 on 2025-12-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0007_paciente_fecha_firma_acudiente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoCIE10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Código CIE-10')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('categoria', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Categoría')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Código CIE-10',
                'verbose_name_plural': 'Códigos CIE-10',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='procedimien_codigo_de053f_idx'), models.Index(fields=['categoria'], name='procedimien_categor_d54c58_idx')],
            },
        ),
    ]
