# Generated by Django 5.0 on 2025-12-16 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0009_codigocie10'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='valoracioninicial',
        #     name='diagnostico_cie10_texto',
        #     field=models.CharField(blank=True, help_text='Código de diagnóstico CIE-10 (si aplica)', max_length=10, verbose_name='Código CIE-10'),
        # ),
        migrations.AddField(
            model_name='valoracioninicial',
            name='diagnostico_cie10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valoraciones', to='procedimientos.codigocie10', verbose_name='Diagnóstico CIE-10'),
        ),
    ]
