# Generated by Django 5.0 on 2025-11-15 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionconsultorio',
            name='consultorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='consultorios.consultorio', verbose_name='Consultorio'),
        ),
        migrations.AlterField(
            model_name='asignacionconsultorio',
            name='terapeuta',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['TERAPEUTA', 'PSICOLOGO', 'MEDICO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultorios_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Terapeuta'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='consultorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salas', to='consultorios.consultorio', verbose_name='Consultorio'),
        ),
    ]
