# Generated by Django 5.0 on 2025-11-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorios', '0002_alter_asignacionconsultorio_consultorio_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='consultorio',
            index=models.Index(fields=['nombre'], name='consultorio_nombre_48a216_idx'),
        ),
        migrations.AddIndex(
            model_name='sala',
            index=models.Index(fields=['nombre'], name='consultorio_nombre_dadd96_idx'),
        ),
        migrations.AddIndex(
            model_name='sala',
            index=models.Index(fields=['fecha_creacion'], name='consultorio_fecha_c_a9e700_idx'),
        ),
    ]
