# Generated by Django 5.0 on 2026-01-19 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorios', '0003_consultorio_consultorio_nombre_48a216_idx_and_more'),
        ('terapias', '0002_alter_terapia_costo_minimo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionconsultorio',
            name='terapia',
            field=models.ForeignKey(blank=True, help_text='Tipo de terapia que se realizará en este consultorio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_consultorio', to='terapias.terapia', verbose_name='Terapia'),
        ),
        migrations.AddIndex(
            model_name='asignacionconsultorio',
            index=models.Index(fields=['terapia'], name='consultorio_terapia_c5c6e0_idx'),
        ),
    ]
