# Generated by Django 5.0 on 2025-11-15 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionterapeutica',
            name='procedimiento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesion_terapeutica', to='procedimientos.procedimiento', verbose_name='Procedimiento Base'),
        ),
    ]
