# Generated by Django 5.0 on 2026-01-19 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedimientos', '0017_alter_paciente_estado'),
        ('terapias', '0002_alter_terapia_costo_minimo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_edad', models.CharField(choices=[('3-6', '3 a 6 años'), ('7-11', '7 a 11 años'), ('12-16', '12 a 16 años')], max_length=10, verbose_name='Rango de Edad')),
                ('titulo', models.CharField(default='INFORME DE TERAPIAS', max_length=200)),
                ('contenido_principal', models.TextField(help_text='Texto predeterminado. Use {nombre_paciente}, {edad}, etc. para campos dinámicos', verbose_name='Contenido del Informe')),
                ('recomendaciones_familia', models.TextField(blank=True, verbose_name='Recomendaciones Familia')),
                ('recomendaciones_escuela', models.TextField(blank=True, verbose_name='Recomendaciones Escolaridad')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_informe', to='terapias.terapia')),
            ],
            options={
                'verbose_name': 'Plantilla de Informe',
                'verbose_name_plural': 'Plantillas de Informes',
                'ordering': ['terapia', 'rango_edad'],
                'unique_together': {('terapia', 'rango_edad')},
            },
        ),
        migrations.CreateModel(
            name='InformeEvolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(verbose_name='Inicio del Período Evaluado')),
                ('periodo_fin', models.DateField(verbose_name='Fin del Período Evaluado')),
                ('contenido_informe', models.TextField(help_text='Texto final del informe (se genera automáticamente de la plantilla)', verbose_name='Contenido del Informe')),
                ('observaciones_especificas', models.TextField(blank=True, help_text='Observaciones adicionales personalizadas', verbose_name='Observaciones Específicas del Profesional')),
                ('firma_profesional', models.ImageField(blank=True, null=True, upload_to='firmas_informes/', verbose_name='Firma del Profesional')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINALIZADO', 'Finalizado'), ('ENVIADO', 'Enviado')], default='BORRADOR', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='informes_pdf/', verbose_name='PDF Generado')),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='procedimientos.admisionterapia', verbose_name='Admisión Relacionada')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_evolucion', to='procedimientos.paciente')),
                ('profesional', models.ForeignKey(limit_choices_to={'rol__in': ['TERAPEUTA', 'MEDICO', 'PSICOLOGO']}, on_delete=django.db.models.deletion.PROTECT, related_name='informes_generados', to=settings.AUTH_USER_MODEL)),
                ('terapia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes', to='terapias.terapia')),
                ('plantilla_usada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reportes.plantillainforme', verbose_name='Plantilla Utilizada')),
            ],
            options={
                'verbose_name': 'Informe de Evolución',
                'verbose_name_plural': 'Informes de Evolución',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
