# Generated by Django 5.0 on 2026-01-11 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedimientos', '0015_codigocie10_nombre_paciente_codigo_enfermedad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_inasistencia_alerta', models.IntegerField(default=3, help_text='Días consecutivos para generar alerta')),
                ('mensaje_sms_template', models.TextField(default='Estimado acudiente, el paciente {nombre} ha faltado {dias} días consecutivos. Por favor comuníquese con la IPS al {telefono_ips}.')),
                ('telefono_ips', models.CharField(default='3001234567', help_text='Teléfono de contacto de la IPS', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Alertas',
                'verbose_name_plural': 'Configuraciones de Alertas',
            },
        ),
        migrations.CreateModel(
            name='AlertaInasistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('dias_consecutivos', models.IntegerField(default=0)),
                ('fecha_ultima_inasistencia', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('NOTIFICADA', 'Notificada'), ('ATENDIDA', 'Atendida'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=20)),
                ('sms_enviado', models.BooleanField(default=False)),
                ('fecha_envio_sms', models.DateTimeField(blank=True, null=True)),
                ('telefono_destino', models.CharField(blank=True, max_length=20)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_inasistencia_atendidas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_inasistencia', to='procedimientos.paciente')),
            ],
            options={
                'verbose_name': 'Alerta de Inasistencia',
                'verbose_name_plural': 'Alertas de Inasistencia',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
