# Generated by Django 5.0 on 2025-11-20 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0002_alter_sesionterapeutica_procedimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_historia_clinica',
            field=models.CharField(blank=True, help_text='Se genera automáticamente si no se especifica (HC-{documento}-{año})', max_length=50, unique=True, verbose_name='Número de Historia Clínica'),
        ),
    ]
