# Generated by Django 5.0 on 2025-11-22 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
        ('procedimientos', '0003_alter_paciente_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado_asignacion',
            field=models.CharField(choices=[('SIN_ASIGNAR', 'Sin Asignar'), ('ASIGNADO', 'Asignado'), ('EN_ESPERA', 'En Espera')], default='SIN_ASIGNAR', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='grupo_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grupos.grupoterapeutico'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tiene_grupo_asignado',
            field=models.BooleanField(default=False),
        ),
    ]
