# Generated by Django 5.0 on 2025-12-04 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_asignaciongrupo_numero_terapias_asignadas_and_more'),
        ('procedimientos', '0004_paciente_estado_asignacion_paciente_grupo_actual_and_more'),
        ('terapias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='numero_admision',
            field=models.CharField(help_text='Número de admisión del paciente (ingresado manualmente)', max_length=50, verbose_name='Número de Admisión'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('ADMITIDO', 'Admitido - Sin Valorar'), ('PENDIENTE_VALORACION', 'Pendiente Valoración'), ('PENDIENTE_ASIGNACION', 'Pendiente Asignación Terapias'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('DADO_ALTA', 'Dado de Alta')], default='ADMITIDO', max_length=30, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ASISTIO', 'Asistió'), ('FALTA', 'Falta'), ('JUSTIFICADA', 'Falta Justificada'), ('TARDANZA', 'Llegó Tarde')], default='ASISTIO', max_length=20, verbose_name='Estado de Asistencia')),
                ('hora_llegada', models.TimeField(blank=True, null=True, verbose_name='Hora de Llegada')),
                ('minutos_retraso', models.PositiveIntegerField(default=0, verbose_name='Minutos de Retraso')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('firma_asistencia', models.TextField(blank=True, help_text='Firma del acudiente confirmando asistencia', verbose_name='Firma Digital')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('asignacion_grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='grupos.asignaciongrupo', verbose_name='Asignación al Grupo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='procedimientos.paciente', verbose_name='Paciente')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
                ('sesion_terapeutica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='procedimientos.sesionterapeutica', verbose_name='Sesión Terapéutica')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'unique_together': {('sesion_terapeutica', 'paciente')},
            },
        ),
        migrations.CreateModel(
            name='ValoracionInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_valoracion', models.CharField(editable=False, help_text='Se genera automáticamente', max_length=50, unique=True, verbose_name='Código de Valoración')),
                ('fecha_valoracion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Valoración')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de Finalización')),
                ('motivo_consulta', models.TextField(help_text='¿Por qué acude el paciente?', verbose_name='Motivo de Consulta')),
                ('antecedentes_personales', models.TextField(blank=True, help_text='Historial médico relevante', verbose_name='Antecedentes Personales')),
                ('antecedentes_familiares', models.TextField(blank=True, help_text='Historial familiar relevante', verbose_name='Antecedentes Familiares')),
                ('desarrollo_evolutivo', models.TextField(blank=True, help_text='Hitos del desarrollo, embarazo, parto, etc.', verbose_name='Desarrollo Evolutivo')),
                ('observaciones_generales', models.TextField(help_text='Impresiones generales del profesional', verbose_name='Observaciones Generales de la Evaluación')),
                ('problemas_detectados', models.JSONField(default=list, help_text='Lista de problemas identificados durante la valoración', verbose_name='Problemas Detectados')),
                ('nivel_funcionalidad', models.CharField(blank=True, choices=[('INDEPENDIENTE', 'Independiente'), ('SEMI_DEPENDIENTE', 'Semi-dependiente'), ('DEPENDIENTE', 'Dependiente')], max_length=20, null=True, verbose_name='Nivel de Funcionalidad')),
                ('evaluacion_lenguaje', models.TextField(blank=True, help_text='Evaluación detallada del área de lenguaje', verbose_name='Evaluación de Lenguaje')),
                ('evaluacion_motora', models.TextField(blank=True, help_text='Evaluación de habilidades motoras', verbose_name='Evaluación Motora')),
                ('evaluacion_cognitiva', models.TextField(blank=True, help_text='Evaluación de funciones cognitivas', verbose_name='Evaluación Cognitiva')),
                ('evaluacion_conductual', models.TextField(blank=True, help_text='Evaluación de comportamiento y conducta', verbose_name='Evaluación Conductual')),
                ('evaluacion_social', models.TextField(blank=True, help_text='Evaluación de habilidades sociales e interacción', verbose_name='Evaluación Social')),
                ('pruebas_aplicadas', models.JSONField(blank=True, default=list, help_text='Tests psicológicos o evaluaciones estandarizadas aplicadas', verbose_name='Pruebas/Tests Aplicados')),
                ('diagnostico_profesional', models.TextField(help_text='Impresión diagnóstica del profesional', verbose_name='Diagnóstico del Profesional')),
                ('diagnostico_cie10', models.CharField(blank=True, help_text='Código de diagnóstico CIE-10 (si aplica)', max_length=10, verbose_name='Código CIE-10')),
                ('numero_sesiones_recomendado', models.PositiveIntegerField(blank=True, help_text='Cantidad total de sesiones sugeridas', null=True, verbose_name='Número de Sesiones Recomendado')),
                ('frecuencia_recomendada', models.CharField(blank=True, help_text='Ej: 2 veces por semana, 3 veces por semana', max_length=100, verbose_name='Frecuencia Recomendada')),
                ('duracion_estimada_tratamiento', models.CharField(blank=True, help_text='Ej: 6 meses, 1 año', max_length=100, verbose_name='Duración Estimada del Tratamiento')),
                ('observaciones_recomendaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el tratamiento recomendado', verbose_name='Observaciones sobre Recomendaciones')),
                ('requiere_interconsulta', models.BooleanField(default=False, help_text='¿Se requiere evaluación de otro especialista?', verbose_name='Requiere Interconsulta')),
                ('especialidades_interconsulta', models.TextField(blank=True, help_text='Ej: Neurología, Psiquiatría, etc.', verbose_name='Especialidades para Interconsulta')),
                ('completada', models.BooleanField(default=False, verbose_name='Valoración Completada')),
                ('fecha_completada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Completación')),
                ('archivos_adjuntos', models.JSONField(blank=True, default=list, help_text='URLs de documentos, imágenes, videos de la valoración', verbose_name='Archivos Adjuntos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='valoracion_inicial', to='procedimientos.paciente', verbose_name='Paciente')),
                ('profesional', models.ForeignKey(limit_choices_to={'rol__in': ['TERAPEUTA', 'MEDICO', 'PSICOLOGO', 'ADMIN']}, on_delete=django.db.models.deletion.PROTECT, related_name='valoraciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Profesional que Valora')),
                ('terapias_recomendadas', models.ManyToManyField(help_text='Tipos de terapias recomendadas para el paciente', related_name='valoraciones', to='terapias.terapia', verbose_name='Terapias Recomendadas')),
            ],
            options={
                'verbose_name': 'Valoración Inicial',
                'verbose_name_plural': 'Valoraciones Iniciales',
                'ordering': ['-fecha_valoracion'],
                'indexes': [models.Index(fields=['paciente'], name='procedimien_pacient_c90da9_idx'), models.Index(fields=['fecha_valoracion'], name='procedimien_fecha_v_1a82cf_idx'), models.Index(fields=['profesional'], name='procedimien_profesi_f34ea8_idx'), models.Index(fields=['completada'], name='procedimien_complet_34e1cb_idx')],
            },
        ),
    ]
