# Generated by Django 5.0 on 2025-12-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0010_valoracioninicial_diagnostico_cie10_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_firma_acudiente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Firma'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='firma_acudiente',
            field=models.TextField(blank=True, help_text='Firma del acudiente en formato base64', verbose_name='Firma Digital Acudiente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ip_firma',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP donde se firmó'),
        ),
    ]
