# Generated by Django 5.0 on 2025-12-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0011_paciente_fecha_firma_acudiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracioninicial',
            name='diagnostico_cie10_texto',
            field=models.CharField(blank=True, help_text='Código de diagnóstico CIE-10 (si aplica)', max_length=10, verbose_name='Código CIE-10'),
        ),
    ]
