# Generated by Django 5.0 on 2025-12-18 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0013_recreate_evolucionpaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='edad_actual',
            field=models.FloatField(blank=True, editable=False, help_text='Edad calculada automáticamente a partir de la fecha de nacimiento', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Edad'),
        ),
    ]
