# Generated by Django 5.0 on 2026-01-11 14:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0007_alertacupo'),
        ('procedimientos', '0014_paciente_edad_actual'),
        ('terapias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codigocie10',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre descriptivo', max_length=200),
        ),
        migrations.AddField(
            model_name='paciente',
            name='codigo_enfermedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='procedimientos.codigocie10', verbose_name='Código CIE-10'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_historia_clinica',
            field=models.CharField(blank=True, help_text='Se genera automáticamente si no se especifica (HC-{documento}-{año})', max_length=50, null=True, unique=True, verbose_name='Número de Historia Clínica'),
        ),
        migrations.CreateModel(
            name='AdmisionTerapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_admision', models.CharField(max_length=50, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad_ordenada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_realizada', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDA', 'Vencida'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='VIGENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admisiones_terapia_creadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admisiones', to='procedimientos.paciente')),
                ('terapia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admisiones_terapia', to='terapias.terapia')),
            ],
            options={
                'verbose_name': 'Admisión por Terapia',
                'verbose_name_plural': 'Admisiones por Terapia',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('asistio', models.BooleanField(default=False)),
                ('justificada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admisiones_asistencias', to='procedimientos.admisionterapia')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asistencias_grupo', to='grupos.grupoterapeutico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asistencias_paciente', to='procedimientos.paciente')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_registradas_sesion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha'],
                'unique_together': {('grupo', 'paciente', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='ValoracionProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_valoracion', models.DateTimeField(auto_now_add=True)),
                ('estado_salud_general', models.TextField()),
                ('observaciones', models.TextField()),
                ('recomendaciones', models.TextField()),
                ('objetivos_terapeuticos', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('REVISADA', 'Revisada')], default='COMPLETADA', max_length=20)),
                ('firma_terapeuta', models.ImageField(blank=True, null=True, upload_to='firmas_valoraciones/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_profesionales', to='procedimientos.paciente')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valoraciones_como_terapeuta', to=settings.AUTH_USER_MODEL)),
                ('terapia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valoraciones_profesionales_terapia', to='terapias.terapia')),
            ],
            options={
                'verbose_name': 'Valoración Profesional',
                'verbose_name_plural': 'Valoraciones Profesionales',
                'ordering': ['-fecha_valoracion'],
                'unique_together': {('paciente', 'terapeuta', 'terapia')},
            },
        ),
    ]
