# Generated by Django 5.0 on 2026-01-14 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0015_codigocie10_nombre_paciente_codigo_enfermedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracionprofesional',
            name='codigo_cie10',
            field=models.ForeignKey(blank=True, help_text='Diagnóstico según clasificación CIE-10', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valoraciones_profesionales', to='procedimientos.codigocie10', verbose_name='Código CIE-10'),
        ),
    ]
