# Generated by Django 5.0 on 2026-01-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0016_valoracionprofesional_codigo_cie10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('ADMITIDO', 'Admitido - Sin Valorar'), ('PENDIENTE_VALORACION', 'Pendiente Valoración'), ('PENDIENTE_ASIGNACION', 'Pendiente Asignación Terapias'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('DADO_ALTA', 'Dado de Alta')], default='ADMITIDO', max_length=30, verbose_name='Estado'),
        ),
    ]
