# Generated by Django 5.0 on 2026-01-12 21:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapia',
            name='costo_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Costo mínimo (si aplica descuento)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo Mínimo'),
        ),
        migrations.AlterField(
            model_name='terapia',
            name='costo_paquete_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Costo de paquete mensual (si aplica)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo Paquete Mensual'),
        ),
        migrations.AlterField(
            model_name='terapia',
            name='costo_sesion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo estándar por sesión individual', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo por Sesión'),
        ),
        migrations.AlterField(
            model_name='terapia',
            name='duracion_maxima_minutos',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='Duración máxima permitida', null=True, validators=[django.core.validators.MaxValueValidator(480)], verbose_name='Duración Máxima (minutos)'),
        ),
        migrations.AlterField(
            model_name='terapia',
            name='duracion_minima_minutos',
            field=models.PositiveIntegerField(blank=True, default=15, help_text='Duración mínima permitida', null=True, validators=[django.core.validators.MinValueValidator(15)], verbose_name='Duración Mínima (minutos)'),
        ),
        migrations.AlterField(
            model_name='terapia',
            name='folleto_url',
            field=models.URLField(blank=True, help_text='Enlace a folleto informativo', null=True, verbose_name='URL del Folleto'),
        ),
        migrations.AlterField(
            model_name='terapia',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enlace a video explicativo', null=True, verbose_name='URL del Video'),
        ),
    ]
