# Generated by Django 5.2.7 on 2025-11-06 01:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Consultorio 101, Sala Azul', max_length=100, unique=True, verbose_name='Nombre del Consultorio')),
                ('codigo', models.CharField(help_text='Código único de identificación', max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('INDIVIDUAL', 'Consultorio Individual'), ('GRUPAL', 'Consultorio Grupal'), ('TERAPIA_FISICA', 'Sala de Terapia Física'), ('TERAPIA_OCUPACIONAL', 'Sala de Terapia Ocupacional'), ('LENGUAJE', 'Sala de Lenguaje'), ('INTEGRACION_SENSORIAL', 'Sala de Integración Sensorial'), ('LUDOTECA', 'Ludoteca/Sala de Juegos'), ('EVALUACION', 'Sala de Evaluación'), ('MUSICOTERAPIA', 'Sala de Musicoterapia')], default='INDIVIDUAL', max_length=30, verbose_name='Tipo de Consultorio')),
                ('piso', models.PositiveIntegerField(help_text='Planta/Piso donde se encuentra', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Piso')),
                ('numero', models.CharField(help_text='Número de consultorio o sala', max_length=20, verbose_name='Número')),
                ('capacidad', models.PositiveIntegerField(default=1, help_text='Número máximo de personas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Capacidad')),
                ('area_metros', models.DecimalField(blank=True, decimal_places=2, help_text='Área en metros cuadrados', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Área (m²)')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('MANTENIMIENTO', 'En Mantenimiento'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('equipamiento', models.JSONField(blank=True, default=list, help_text='Lista de equipamiento disponible en el consultorio', verbose_name='Equipamiento')),
                ('caracteristicas', models.TextField(blank=True, help_text='Descripción de características especiales', verbose_name='Características')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='consultorios/fotos/', verbose_name='Foto del Consultorio')),
                ('tiene_ventana', models.BooleanField(default=True, verbose_name='Tiene Ventana')),
                ('tiene_aire_acondicionado', models.BooleanField(default=False, verbose_name='Tiene Aire Acondicionado')),
                ('accesible_silla_ruedas', models.BooleanField(default=True, verbose_name='Accesible para Silla de Ruedas')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
                'ordering': ['piso', 'numero'],
                'indexes': [models.Index(fields=['codigo'], name='consultorio_codigo_a6083b_idx'), models.Index(fields=['tipo', 'estado'], name='consultorio_tipo_197e4d_idx'), models.Index(fields=['piso', 'numero'], name='consultorio_piso_d040fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionConsultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_asignacion', models.CharField(choices=[('PERMANENTE', 'Asignación Permanente'), ('TEMPORAL', 'Asignación Temporal'), ('COMPARTIDA', 'Asignación Compartida')], default='TEMPORAL', max_length=15, verbose_name='Tipo de Asignación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar en blanco para asignaciones permanentes', null=True, verbose_name='Fecha de Fin')),
                ('horario', models.JSONField(blank=True, default=dict, help_text='Horario de uso del consultorio por día', verbose_name='Horario')),
                ('dias_semana', models.JSONField(blank=True, default=list, help_text='Lista de días asignados: ["Lunes", "Martes", ...]', verbose_name='Días de la Semana')),
                ('prioridad', models.PositiveIntegerField(default=1, help_text='1=Baja, 5=Alta', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Prioridad')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('activo', models.BooleanField(default=True, verbose_name='Asignación Activa')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('terapeuta', models.ForeignKey(limit_choices_to={'rol__in': ['TERAPEUTA', 'PSICOLOGO', 'MEDICO']}, on_delete=django.db.models.deletion.CASCADE, related_name='consultorios_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Terapeuta')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='consultorios.consultorio', verbose_name='Consultorio')),
            ],
            options={
                'verbose_name': 'Asignación de Consultorio',
                'verbose_name_plural': 'Asignaciones de Consultorios',
                'ordering': ['-fecha_inicio', '-prioridad'],
                'indexes': [models.Index(fields=['consultorio', 'terapeuta'], name='consultorio_consult_5ca142_idx'), models.Index(fields=['fecha_inicio', 'fecha_fin'], name='consultorio_fecha_i_4054c4_idx'), models.Index(fields=['activo'], name='consultorio_activo_4111a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadConsultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('OCUPADO', 'Ocupado'), ('BLOQUEADO', 'Bloqueado')], default='DISPONIBLE', max_length=15, verbose_name='Estado')),
                ('motivo_bloqueo', models.CharField(blank=True, help_text='Solo si el estado es Bloqueado', max_length=200, verbose_name='Motivo de Bloqueo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='consultorios.consultorio', verbose_name='Consultorio')),
                ('terapeuta', models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['TERAPEUTA', 'PSICOLOGO', 'MEDICO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disponibilidades_consultorio', to=settings.AUTH_USER_MODEL, verbose_name='Terapeuta Asignado')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Consultorio',
                'verbose_name_plural': 'Disponibilidades de Consultorios',
                'ordering': ['fecha', 'hora_inicio'],
                'indexes': [models.Index(fields=['consultorio', 'fecha'], name='consultorio_consult_d16c7a_idx'), models.Index(fields=['estado'], name='consultorio_estado_6139a3_idx'), models.Index(fields=['terapeuta', 'fecha'], name='consultorio_terapeu_fa7837_idx')],
                'unique_together': {('consultorio', 'fecha', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Sala')),
                ('tipo', models.CharField(choices=[('EVALUACION', 'Área de Evaluación'), ('TERAPIA', 'Área de Terapia'), ('JUEGO', 'Área de Juego'), ('ESPERA', 'Área de Espera'), ('OBSERVACION', 'Área de Observación'), ('MATERIAL', 'Área de Material')], max_length=20, verbose_name='Tipo de Sala')),
                ('area_metros', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Área (m²)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('equipamiento_especifico', models.JSONField(blank=True, default=list, verbose_name='Equipamiento Específico')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='consultorios.consultorio', verbose_name='Consultorio')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['consultorio', 'nombre'],
                'unique_together': {('consultorio', 'nombre')},
            },
        ),
    ]
