# Generated by Django 5.0 on 2025-11-22 23:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedimientos', '0003_alter_paciente_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTerapeutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Grupo 9:00 a.m.', max_length=100, unique=True, verbose_name='Nombre del Grupo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('hora_inicio', models.TimeField(help_text='Hora en que inicia la sesión grupal', verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(help_text='Hora en que finaliza la sesión grupal', verbose_name='Hora de Fin')),
                ('dias_disponibles', models.JSONField(default=list, help_text='Lista de días en que funciona el grupo. Ej: ["L","M","X","J","V"]', verbose_name='Días Disponibles')),
                ('capacidad_maxima', models.PositiveIntegerField(default=10, help_text='Número máximo de pacientes que pueden estar asignados al grupo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Capacidad Máxima')),
                ('pacientes_actuales', models.PositiveIntegerField(default=0, help_text='Número actual de pacientes asignados (se actualiza automáticamente)', verbose_name='Pacientes Actuales')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Adicionales')),
            ],
            options={
                'verbose_name': 'Grupo Terapéutico',
                'verbose_name_plural': 'Grupos Terapéuticos',
                'ordering': ['hora_inicio', 'nombre'],
                'indexes': [models.Index(fields=['activo', 'hora_inicio'], name='grupos_grup_activo_0c01a1_idx'), models.Index(fields=['capacidad_maxima', 'pacientes_actuales'], name='grupos_grup_capacid_febdd5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_asistencia', models.JSONField(default=list, help_text='Días en que el paciente asiste. Ej: ["L","M","X"]', verbose_name='Días de Asistencia')),
                ('numero_terapias_semanales', models.PositiveIntegerField(default=3, help_text='Cantidad de sesiones terapéuticas por semana', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Número de Terapias Semanales')),
                ('fecha_inicio_asignacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('fecha_fin_asignacion', models.DateField(blank=True, help_text='Fecha en que finalizó la asignación', null=True, verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('motivo_suspension', models.TextField(blank=True, verbose_name='Motivo de Suspensión/Finalización')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_grupo', to='procedimientos.paciente', verbose_name='Paciente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='grupos.grupoterapeutico', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Asignación a Grupo',
                'verbose_name_plural': 'Asignaciones a Grupos',
                'ordering': ['-fecha_inicio_asignacion'],
                'indexes': [models.Index(fields=['estado', 'fecha_inicio_asignacion'], name='grupos_asig_estado_3dffc7_idx'), models.Index(fields=['paciente', 'estado'], name='grupos_asig_pacient_f7f40c_idx'), models.Index(fields=['grupo', 'estado'], name='grupos_asig_grupo_i_b25252_idx')],
                'unique_together': {('paciente', 'grupo', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='PacientePendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferencia_horario', models.TimeField(help_text='Hora preferida para asistir', verbose_name='Horario Preferido')),
                ('dias_preferidos', models.JSONField(default=list, help_text='Días en que puede asistir. Ej: ["L","M","X"]', verbose_name='Días Preferidos')),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Asignación'), ('ASIGNADO', 'Asignado a Grupo'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_asignacion', models.DateTimeField(blank=True, help_text='Fecha en que fue asignado a un grupo', null=True, verbose_name='Fecha de Asignación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('motivo_cancelacion', models.TextField(blank=True, verbose_name='Motivo de Cancelación')),
                ('grupo_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_asignados_desde_pendientes', to='grupos.grupoterapeutico', verbose_name='Grupo Asignado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_pendientes', to='procedimientos.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Paciente Pendiente de Asignación',
                'verbose_name_plural': 'Pacientes Pendientes de Asignación',
                'ordering': ['-prioridad', 'fecha_solicitud'],
                'indexes': [models.Index(fields=['estado', 'prioridad', 'fecha_solicitud'], name='grupos_paci_estado_9071b8_idx'), models.Index(fields=['paciente', 'estado'], name='grupos_paci_pacient_e1addd_idx')],
            },
        ),
    ]
