# Generated by Django 5.0 on 2025-12-04 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciongrupo',
            name='numero_terapias_asignadas',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad total de sesiones programadas', verbose_name='Número Total de Terapias Asignadas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignaciongrupo',
            name='terapias_completadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Terapias Completadas'),
        ),
        migrations.AlterField(
            model_name='asignaciongrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='grupos.grupoterapeutico', verbose_name='Grupo Terapéutico'),
        ),
    ]
