# Generated by Django 5.0 on 2025-12-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_asignaciongrupo_numero_terapias_asignadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciongrupo',
            name='numero_terapias_asignadas',
            field=models.PositiveIntegerField(default=10, help_text='Cantidad total de sesiones programadas', verbose_name='Número Total de Terapias Asignadas'),
        ),
    ]


