# Generated by Django 5.0 on 2026-01-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_alter_asignaciongrupo_numero_terapias_asignadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoterapeutico',
            name='edad_minima',
            field=models.DecimalField(blank=True, decimal_places=0, default=2, help_text='Edad mínima requerida para pertenecer al grupo', max_digits=2, null=True, verbose_name='Edad Mínima (años)'),
        ),
    ]
