# Generated by Django 5.0 on 2026-01-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0004_grupoterapeutico_edad_minima'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoterapeutico',
            name='edad_maxima',
            field=models.DecimalField(blank=True, decimal_places=0, default=20, help_text='Edad máxima permitida para pertenecer al grupo', max_digits=2, null=True, verbose_name='Edad Máxima (años)'),
        ),
    ]
