# Generated by Django 5.0 on 2026-01-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0005_grupoterapeutico_edad_maxima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoterapeutico',
            name='edad_maxima',
            field=models.FloatField(blank=True, default=20, help_text='Edad máxima permitida para pertenecer al grupo', null=True, verbose_name='Edad Máxima (años)'),
        ),
        migrations.AlterField(
            model_name='grupoterapeutico',
            name='edad_minima',
            field=models.FloatField(blank=True, default=2, help_text='Edad mínima requerida para pertenecer al grupo', null=True, verbose_name='Edad Mínima (años)'),
        ),
    ]
