# Generated by Django 5.0 on 2026-01-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0006_alter_grupoterapeutico_edad_maxima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaCupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad_anterior', models.IntegerField()),
                ('capacidad_nueva', models.IntegerField()),
                ('pacientes_excedentes', models.IntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de reasignación'), ('EN_PROCESO', 'En proceso'), ('RESUELTA', 'Resuelta')], default='PENDIENTE', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Alerta de Cupo',
                'verbose_name_plural': 'Alertas de Cupo',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
