# Generated by Django 5.0 on 2026-01-11 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0007_alertacupo'),
        ('procedimientos', '0015_codigocie10_nombre_paciente_codigo_enfermedad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciongrupo',
            name='admision_terapia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='procedimientos.admisionterapia'),
        ),
        migrations.AddField(
            model_name='asignaciongrupo',
            name='alerta_inasistencia_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asignaciongrupo',
            name='dias_inasistencias_consecutivas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asignaciongrupo',
            name='fecha_ultima_asistencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertacupo',
            name='generada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_cupo_generadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertacupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_cupo', to='grupos.grupoterapeutico'),
        ),
        migrations.AddField(
            model_name='alertacupo',
            name='resuelta_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas_cupo_resueltas', to=settings.AUTH_USER_MODEL),
        ),
    ]
