# Generated by Django 5.0 on 2026-01-13 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0008_asignaciongrupo_admision_terapia_and_more'),
        ('terapias', '0002_alter_terapia_costo_minimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoterapeutico',
            name='terapia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='terapia_GrupoTerapeutico', to='terapias.terapia'),
        ),
    ]
