# Generated by Django 5.0 on 2026-01-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0009_grupoterapeutico_terapia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoterapeutico',
            name='terapia',
        ),
    ]
