# Generated by Django 5.0 on 2026-01-13 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0010_remove_grupoterapeutico_terapia'),
        ('terapias', '0002_alter_terapia_costo_minimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoterapeutico',
            name='terapia',
            field=models.ForeignKey(blank=True, help_text='Tipo de terapia que ofrece este grupo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos_terapeuticos', to='terapias.terapia', verbose_name='Terapia'),
        ),
    ]
