# Generated by Django 5.0 on 2026-01-16 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0011_grupoterapeutico_terapia'),
        ('procedimientos', '0016_valoracionprofesional_codigo_cie10'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha')),
                ('asistio', models.BooleanField(default=True, verbose_name='Asistió')),
                ('justificada', models.BooleanField(default=False, help_text='Marcar si la falta está justificada', verbose_name='Inasistencia Justificada')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to='grupos.asignaciongrupo', verbose_name='Asignación')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='grupos.grupoterapeutico', verbose_name='Grupo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_grupo', to='procedimientos.paciente', verbose_name='Paciente')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Usuario_registra', to=settings.AUTH_USER_MODEL, verbose_name='Registró asistencia')),
            ],
            options={
                'verbose_name': 'Asistencia de Paciente',
                'verbose_name_plural': 'Asistencias de Pacientes',
                'ordering': ['-fecha', 'paciente__apellidos'],
                'indexes': [models.Index(fields=['fecha', 'grupo'], name='grupos_asis_fecha_83fc56_idx'), models.Index(fields=['paciente', 'fecha'], name='grupos_asis_pacient_0c5c3b_idx'), models.Index(fields=['asistio'], name='grupos_asis_asistio_d56d94_idx')],
                'unique_together': {('paciente', 'grupo', 'fecha')},
            },
        ),
    ]
