# Generated by Django 5.0 on 2026-01-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0012_asistenciapaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciongrupo',
            name='numero_terapias_asignadas',
            field=models.PositiveIntegerField(default=20, help_text='Cantidad total de sesiones programadas', verbose_name='Número Total de Terapias Asignadas'),
        ),
    ]
